import { ArrowLeft, CheckCircle2, ImageOff } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { useState } from "react";
import categories from "../data/categories.json";
import medicines from "../data/medicines.json";

export default function ProductDetails() {
  const { id } = useParams(); const medicine = medicines.find((item) => item.id === id); const [imageError, setImageError] = useState(false);
  if (!medicine) return <main className="container-app flex min-h-[70vh] flex-col items-center justify-center pt-24 text-center"><p className="eyebrow">Product not found</p><h1 className="mt-3 text-3xl font-semibold">This medicine is not in the catalogue.</h1><Link to="/products" className="btn-primary mt-7">Back to products</Link></main>;
  const category = categories.find((item) => item.id === medicine.category);
  return <main className="pb-24 pt-28"><div className="container-app"><Link to="/products" className="inline-flex items-center gap-2 text-sm font-semibold text-navy hover:text-medgreen"><ArrowLeft size={16} /> Back to products</Link><div className="mt-8 grid gap-10 lg:grid-cols-[.92fr_1.08fr] lg:gap-16"><div className="flex min-h-[360px] items-center justify-center rounded-[2rem] bg-[#edf3f4] p-10">{imageError ? <div className="text-center text-navy/45"><ImageOff className="mx-auto" size={32} /><p className="mt-3 text-sm">Product image coming soon</p></div> : <img src={medicine.image} alt={medicine.name} onError={() => setImageError(true)} className="max-h-[430px] w-full object-contain" />}</div><div><p className="eyebrow">{category?.name || "Medicine"}</p><h1 className="mt-4 text-4xl font-semibold sm:text-5xl">{medicine.name}</h1><p className="mt-5 text-lg font-medium text-medgreen">{medicine.composition}</p><p className="mt-6 leading-8 text-ink/70">{medicine.description}</p><dl className="mt-8 grid gap-4 border-y border-line py-6 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-[.12em] text-ink/45">Dosage form</dt><dd className="mt-2 font-medium text-navy">{medicine.dosageForm}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-[.12em] text-ink/45">Packaging</dt><dd className="mt-2 font-medium text-navy">{medicine.packaging}</dd></div></dl><div className="mt-8"><h2 className="text-xl font-semibold">Common uses</h2><ul className="mt-4 space-y-3">{medicine.uses.map((use) => <li key={use} className="flex gap-3 text-sm leading-6 text-ink/70"><CheckCircle2 className="mt-0.5 shrink-0 text-medgreen" size={18} />{use}</li>)}</ul></div><p className="mt-8 rounded-xl bg-[#f3f7f6] p-4 text-xs leading-5 text-ink/60">Product information is provided for professional reference. Please use medicines only under the guidance of a qualified healthcare professional.</p></div></div></div></main>;
}
